I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script3.rpy", line 583, in script
    jump chapter1_5
ScriptError: could not find label 'chapter1_5'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script3.rpy", line 583, in script
    jump chapter1_5
  File "C:\Users\Admin\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 1992, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\Admin\Desktop\renpy-8.1.3-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'chapter1_5'.

Windows-10-10.0.18363 AMD64
Ren'Py 8.1.3.23091805
test2 1.0
Sat Jan  6 23:11:08 2024
