I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 13, in script
    image me = Live2D("images/runtime", base=.6, loop = "true")
  File "game/script.rpy", line 13, in <module>
    image me = Live2D("images/runtime", base=.6, loop = "true")
Exception: Could not load Live2D. b'Live2DCubismCore.dll' was not found.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 13, in script
    image me = Live2D("images/runtime", base=.6, loop = "true")
  File "C:\Users\Administrator\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1237, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Administrator\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 13, in <module>
    image me = Live2D("images/runtime", base=.6, loop = "true")
  File "C:\Users\Administrator\Downloads\renpy-8.1.3-sdk\renpy\gl2\live2d.py", line 566, in __init__
    common = self.create_common(default_fade)
  File "C:\Users\Administrator\Downloads\renpy-8.1.3-sdk\renpy\gl2\live2d.py", line 510, in create_common
    rv = Live2DCommon(self.filename, default_fade)
  File "C:\Users\Administrator\Downloads\renpy-8.1.3-sdk\renpy\gl2\live2d.py", line 186, in __init__
    init()
  File "C:\Users\Administrator\Downloads\renpy-8.1.3-sdk\renpy\gl2\live2d.py", line 93, in init
    onetime_init()
  File "C:\Users\Administrator\Downloads\renpy-8.1.3-sdk\renpy\gl2\live2d.py", line 66, in onetime_init
    raise Exception("Could not load Live2D. {} was not found.".format(dll))
Exception: Could not load Live2D. b'Live2DCubismCore.dll' was not found.

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Dimension 1.0
Tue Mar 12 20:41:25 2024
